Title = "Lyu's Daily"
LanguageCode = "en-us"
BaseUrl = "https://lvliangxiong.github.io/"
Theme = "next"
MetaDataFormat = "yaml"
CanonifyUrls = true
BuildDrafts = false
PaginatePath = "paginate"
Paginate = 8
DisablePathToLower = false
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
PygmentsStyle = "vs"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
DefaultContentLanguage = "en"

[Params]
Introduce = "To Be A Programmer"
Description = "Blog | Software | Java | Python"
Keywords = "Lyu's Daily, Java, Python"
Subtitle = "a little bit change"
Imglogo = "/img/logo.png"
AuthorImg = "/img/author.jpg"
DateFormat = "2006-01-02"
YearFormat = "2006"
MonthFormat = "01-02"
Fancybox = true
StartYear = "2019"

[Author]
Name = "JoeyLyu"

[Params.Share]
Baidu = true

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[[Menu.Main]]
Name = "Home"
Pre = "home"
URL = "/"
Weight = 1

[[Menu.Main]]
Name = "Java"
Pre = "code"
URL = "/categories/java/"
Weight = 2

[[Menu.Main]]
Name = "Python"
Pre = "tint"
URL = "/categories/python/"
Weight = 3

[[Menu.Main]]
Name = "Archive"
Pre = "archive"
URL = "/post/"
Weight = 4

[[Menu.Main]]
Name = "About"
Pre = "user"
URL = "/about/"
Weight = 5

[[Params.Socials]]
Name = "GitHub"
Icon = "github"
URL = "https://github.com/lvliangxiong/"
